trainer:
  gpus: 1
  num_nodes: 1

model:
  # needed to initialize megatron
  micro_batch_size: 1
  tensor_model_parallel_size: 1
  encoder_seq_length: 512
  num_layers: 1
  hidden_size: 16
  vocab_file: /raid/data/gpt/vocab.json
  merge_file: /raid/data/gpt/merges.txt

  # GPT
  pre_process: True
  post_process: True

  train_ds:
    data_prefix: 
      - /raid/data/gpt/simple_wiki_gpt_preproc_text_document
    data_impl: mmap
    splits_string: 949,50,1
    train_valid_test_num_samples:
      - 10000
      - 100
      - 100
    seq_length: ${model.encoder_seq_length}
    seed: 123
    skip_warmup: False
    num_workers: 0


