trainer:
  gpus: 4
  num_nodes: 1
  accelerator: ddp
  precision: 16
  logger: False
  checkpoint_callback: False
  replace_sampler_ddp: False
  max_epochs: null
  max_steps: 5000000
  log_every_n_steps: 100
  val_check_interval: 2000
  limit_val_batches: 50
  gradient_clip_val: 1.0

exp_manager:
  # TODO: add always save nemo
  exp_dir: /raid/nemo_experiments/
  name: megatron_gpt
  create_wandb_logger: True
  wandb_logger_kwargs:
    project: nemo_megatron_gpt_pretraining
    name: dev
  create_checkpoint_callback: True
  checkpoint_callback_params:
    monitor: val_loss
    save_top_k: 10
    mode: min
    always_save_nemo: False

model:
  debug: False # logs debugging info
  # add validation generation config, size of context, m
  # needed to initialize megatron
  micro_batch_size: 16
  tensor_model_parallel_size: 2
  max_position_embeddings: 1024
  encoder_seq_length: 1024
  num_layers: 24
  hidden_size: 1024
  num_attention_heads: 16
  vocab_file: /raid/data/gpt/vocab.json
  merge_file: /raid/data/gpt/merges.txt
  seed: 1234

  # GPT
  pre_process: True
  post_process: True

  data:
    # data_prefix
      # weight 
      # path
    data_prefix: 
      - .5
      - /raid/data/pile/my-gpt3_00_text_document
      - .5
      - /raid/data/pile/my-gpt3_01_text_document
      #- /raid/data/gpt/simple_wiki_gpt_preproc_text_document
    data_impl: mmap
    splits_string: 949,50,1
    seq_length: ${model.encoder_seq_length}
    skip_warmup: False
    num_workers: 0
    dataloader_type: single # cyclic
  
  optim:
    name: adam
    lr: 0.00015
    weight_decay: 0.1
    betas: 
    - 0.9
    - 0.999
    sched:
      name: CosineAnnealing
      warmup_steps: 50000
